"""PR Publisher — commit artifacts, push the worktree branch, open a PR via gh.

Never force-pushes. Never touches main/master. The branch name is derived from
the task_id and was already created by the Coder's `git worktree add -B`.
"""

from __future__ import annotations

import subprocess
import time
from pathlib import Path

from dev_graph.state import DevState, TraceEntry


def run(state: DevState) -> dict:
    start = time.time()
    ws = Path(state["workspace_path"]).resolve()
    branch = f"devgraph/{state['task_id']}"
    spec = state["spec"]
    title = f"[devgraph] {spec.summary[:60]}"

    body_lines = [
        "## Summary",
        spec.summary,
        "",
        "## Acceptance criteria",
        *[f"- [ ] {ac}" for ac in spec.acceptance_criteria],
        "",
        "## Affected components",
        ", ".join(spec.affected_components) or "(none listed)",
        "",
        "## Trace",
    ]
    for t in state.get("trace", []):
        node = getattr(t, "node", None) or (t.get("node") if isinstance(t, dict) else "?")
        ms = getattr(t, "duration_ms", 0) or (t.get("duration_ms", 0) if isinstance(t, dict) else 0)
        summary = getattr(t, "summary", "") or (t.get("summary", "") if isinstance(t, dict) else "")
        body_lines.append(f"- **{node}** ({ms}ms) — {summary}")
    body_lines += ["", "Generated by dev-graph (Phase 1)."]
    body = "\n".join(body_lines)

    # Stage everything the coder wrote in this worktree.
    _run(["git", "add", "-A"], ws)
    # Commit; ignore failure (e.g. nothing to commit).
    _run(["git", "commit", "-m", f"devgraph: {spec.summary}"], ws, check=False)

    # Push. Requires the remote to exist.
    push = _run(["git", "push", "-u", "origin", branch], ws, check=False, capture=True)
    push_ok = push.returncode == 0

    pr_url = ""
    if push_ok:
        pr = _run(
            ["gh", "pr", "create", "--title", title, "--body", body, "--head", branch],
            ws, check=False, capture=True,
        )
        if pr.returncode == 0:
            pr_url = pr.stdout.strip()

    duration = int((time.time() - start) * 1000)
    summary = pr_url or ("push failed" if not push_ok else "gh pr create failed")
    return {
        "pr_url": pr_url,
        "trace": [TraceEntry(node="pr_publisher", duration_ms=duration, summary=summary)],
    }


def _run(cmd: list[str], cwd: Path, check: bool = True, capture: bool = False):
    return subprocess.run(
        cmd, cwd=cwd, check=check,
        capture_output=capture, text=True,
    )
